pipeline:

#  build:
#   image: ukhomeoffice/drone-docker
#   repo: quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb
#   secrets: [ docker_username, docker_password ]
#   registry: quay.io
#   when:
#     event: push

  build_tag:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    dry_run: true 
    environment:
      - VERSION=${DRONE_TAG}
    when:
      event: pull-request

  build_tag:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb
    autotag: true
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    mem_limit: 8000000000
    environment:
      - VERSION=${DRONE_TAG}
    when:
      event: tag
