pipeline:

  build:
    image: ukhomeoffice/drone-docker
    repo: quay.io/ukhomeofficedigital/docker-tinkerpop-graphdb
    secrets: [ docker_username, docker_password ]
    registry: quay.io
    when:
      event: push
